### ISSUE TITLE
Crash at block 14954374

### ISSUE THREAD

**Issue by fafrd** [crypt0biwan/curio-sales-bot#11]
Jun 12 10:50:27 PM  > curio-sales-bot@1.0.0 start
Jun 12 10:50:27 PM  > node server.js
Jun 12 10:50:27 PM  
Jun 12 10:50:29 PM  new block: 14954374
Jun 12 10:50:31 PM  /opt/render/project/src/utils/watcher.js:127
Jun 12 10:50:31 PM              let qty = curioLog.args._value.toNumber();
Jun 12 10:50:31 PM                                             ^
Jun 12 10:50:31 PM  
Jun 12 10:50:31 PM  TypeError: Cannot read properties of undefined (reading 'toNumber')    at handleCurioTransfer (/opt/render/project/src/utils/watcher.js:127:34)    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async InfuraProvider.<anonymous> (/opt/render/project/src/utils/watcher.js:152:20)

**Comment by fafrd** [comment]
I'm not sure why this would cause a crash. When I test with `events = await getEventsFromBlock(14954374)`, `events` is an empty array. Nor is there an apparent curio transfer at this point. Maybe this is a reorg?

**Comment by fafrd** [comment]
maybe just need some error handing around `watcher.js:127`. i'll wait and see if this happens again
